#!/usr/bin/env bash
# This script configures the nginx server so that /redirect_me is redirected.

sudo apt update -y
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
