#!/usr/bin/env bash
# setting up server to curl port 80 with no issues

sudo apt-get update
sudo apt-get -y install curl
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default  /etc/nginx/sites-enabled/default
sudo service nginx restart
