#!/usr/bin/env bash
# Installing new server to serve content

sudo ln -sf /etc/nginx/sites-available/default  /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"
