#!/usr/bin/env bash
# displays Best School 10 times.

a=1
while [ $a -le 100 ]
do
    if [ $((a%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((a%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((a%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$a"
    fi
    (( a++ )) || true
done
