#!/usr/bin/env bash
# displays Best School 10 times.

a=1
while [ $a -le 10 ]
do
    if [ $a = 4 ]
    then
        echo "bad luck"
    elif [ $a = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( a++ )) || true
done
